### ISSUE TITLE
Permission must be changed before script can be run

### ISSUE THREAD

**Issue by jonocosa** [notlmn/.dotfiles#1]
I used chmod x+u to change the permission of utils.sh and main.sh after that the script work fine for me.

**Comment by ramlmn** [comment]
@jonocosa I'am no expert on permissions. Please can you elaborate the issue - were you not able to run the script without changing permissions?

**Comment by jonocosa** [comment]
@ramlmn yes I changed it, chmod u+x will make the file executable for the user. In linux you have to be the owner of a script in order to run it. If you want I can add a note to the readme.

**Comment by ramlmn** [comment]
Wouldn't that be automatically the username of the one who cloned the repo?

I presume you may have downloaded it. Thanks for letting me know that.

Closing this for now, because I suppose that every Linux user already knows how to run a script.

Feel free to reopen this if you have any further problems.

**Comment by ramlmn** [comment]
Sorry to be late, but should be fixed in 23c8e89c2ddb6c46b6a430ef6f7b062aba7b8620
